---
version: "3"

vars:
  DEVICE_LABEL: "JBGPG"
  BACKUP_NAME: "all-secret-keys.asc"
  FINGERPRINT: "DE99604016EF8893AD54FDE83BC85C121EA96233"
  KEY_NAME: "jbgpg"
  DEVICE:
    sh: blkid -L {{ .DEVICE_LABEL }} || echo ""
  GPGDIR:
    sh: echo "${GNUPGHOME:-$HOME/.gnupg}"
  MOUNTDIR:
    sh: echo "/run/media/$USER/{{ .DEVICE_LABEL }}"
  GPG:
    sh: which gpg

tasks:
  mount-disk:
    run: once
    cmds:
      - mkdir -p {{ .MOUNTDIR }}
      - udisksctl mount --block-device {{ .DEVICE }} || sudo diskutil mount -mountPoint {{.MOUNTDIR}} {{ .DEVICE_LABEL }}

  unmount-disk:
    run: once
    cmds:
      - udisksctl unmount --block-device {{ .DEVICE }} || sudo diskutil unmount {{ .DEVICE_LABEL }}

  ensure-gpgdir:
    run: once
    cmds:
      - mkdir -p {{ .GPGDIR }}
      - chown -R $(whoami) {{ .GPGDIR }}
      - find {{ .GPGDIR }} -type f -exec chmod 600 {} \;
      - find {{ .GPGDIR }} -type d -exec chmod 700 {} \;

  offline-key:
    desc: Exports a key to offline.
    cmds:
      - task: mount-disk
      - defer: { task: unmount-disk }
      - "{{.GPG}} -a --export {{ .FINGERPRINT }} > {{ .MOUNTDIR }}/{{ .KEY_NAME }}.pub.asc"
      - "{{.GPG}} -a --export-secret-keys {{ .FINGERPRINT }} > {{ .MOUNTDIR }}/{{ .KEY_NAME }}.pri.asc"
      - "{{.GPG}} -a --export-secret-subkeys {{ .FINGERPRINT }} > {{ .MOUNTDIR }}/{{ .KEY_NAME }}.sub.asc"
      - "{{.GPG}} -a --gen-revoke {{ .FINGERPRINT }} > {{ .MOUNTDIR }}/{{ .KEY_NAME }}.rev.asc"
      - "{{.GPG}} --export-ownertrust > {{ .MOUNTDIR }}/trust-db-backup.txt"
      - gpg-connect-agent "DELETE_KEY {{ .KEYGRIP }}" /bye
      - "{{.GPG}} --list-secret-keys"
    interactive: true
    vars:
      KEYGRIP:
        sh: "{{.GPG}} --list-secret-keys --with-keygrip | grep Keygrip | sed '1!d' | cut -f2 -d="

  online-full-key:
    desc: Imports the full keyring to use online.
    cmds:
      - task: mount-disk
      - defer: { task: unmount-disk }
      - task: ensure-gpgdir
      - rm {{ .GPGDIR }}/trustdb.gpg || true
      - "{{.GPG}} --import {{ .MOUNTDIR }}/{{ .KEY_NAME }}.pub.asc"
      - "{{.GPG}} --import {{ .MOUNTDIR }}/{{ .KEY_NAME }}.pri.asc"
      - task: online-partial-key

  online-partial-key:
    desc: Imports the subkeys to use online.
    cmds:
      - task: mount-disk
      - defer: { task: unmount-disk }
      - task: ensure-gpgdir
      - rm {{ .GPGDIR }}/trustdb.gpg || true
      - "{{.GPG}} --import {{ .MOUNTDIR }}/{{ .KEY_NAME }}.sub.asc"
      - "{{.GPG}} --import-ownertrust < {{ .MOUNTDIR }}/trust-db-backup.txt"

  publish-keys:
    cmds:
      - "{{.GPG}} --keyserver hkps://keys.openpgp.org --send-keys {{ .FINGERPRINT }}"
      - "{{.GPG}} --keyserver hkp://keyserver.ubuntu.com --send-keys {{ .FINGERPRINT }}"
